version: "3.3"
services:
  live-tests-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./livetests/:/usr/src/app/
      - ~/.pdbrc.py:/root/.pdbrc.py
      - ~/.pdbrc:/root/.pdbrc
    command: tail -f __init__.py
    environment:
      - ENV=qa
    stdin_open: true
    tty: true
