name: Live Tests

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  packages: write

env:
  IMAGE: docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/live-tests
  CONTAINER_NAME: live-tests
  DOCKER_FILE: ./livetests/Dockerfile
  DOCKER_BUILD_DIR: ./livetests

jobs:
  live-tests:
    name: Run Live Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3.6.0
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE }} || true
      - name: Build image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }} \
            --tag ${{ env.IMAGE }} \
            --file ${{ env.DOCKER_FILE }} \
            "${{ env.DOCKER_BUILD_DIR }}"
      - name: mkdir allure-results-qa
        if: always()
        run: |
          mkdir livetests/livetests/allure-results-qa
      - name: debug
        if: always()
        run: |
          ls -la gh-pages/qa
      - name: Run live tests on qa
        run: |
          cd ${{ env. DOCKER_BUILD_DIR }} && docker run \
            --rm \
            --name ${{ env.CONTAINER_NAME }} \
            --volume './livetests/allure-results-qa:/usr/src/app/allure-results' \
            -e ENV="qa" \
            ${{ env.IMAGE }} \
            python -m pytest -v -s --tb=short --alluredir allure-results
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: livetests/livetests/allure-results-qa
          allure_history: qa/allure-history
          allure_report: qa/allure-report
          subfolder: qa
      - name: debug
        if: always()
        run: |
          ls -la
      - name: debug
        if: always()
        run: |
          ls -la gh-pages/qa
      - name: mkdir allure-results-staging
        if: always()
        run: |
          mkdir livetests/livetests/allure-results-staging
      - name: debug
        if: always()
        run: |
          ls -la gh-pages/staging
      - name: Run live tests on staging
        if: always()
        run: |
          cd ${{ env. DOCKER_BUILD_DIR }} && docker run \
            --rm \
            --name ${{ env.CONTAINER_NAME }} \
            --volume './livetests/allure-results-staging:/usr/src/app/allure-results' \
            -e ENV="staging" \
            ${{ env.IMAGE }} \
            python -m pytest -v -s --tb=short --alluredir allure-results
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: livetests/livetests/allure-results-staging
          allure_history: staging/allure-history
          allure_report: staging/allure-report
          subfolder: staging
      - name: debug
        if: always()
        run: |
          ls -la gh-pages/staging
      - name: mkdir allure-results-prod
        if: always()
        run: |
          mkdir livetests/livetests/allure-results-prod
      - name: Run live tests on prod
        if: always()
        run: |
          cd ${{ env. DOCKER_BUILD_DIR }} && docker run \
            --rm \
            --name ${{ env.CONTAINER_NAME }} \
            --volume './livetests/allure-results-prod:/usr/src/app/allure-results' \
            -e ENV="prod" \
            ${{ env.IMAGE }} \
            python -m pytest -v -s --tb=short --alluredir allure-results
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: livetests/livetests/allure-results-prod
          allure_history: prod/allure-history
          allure_report: prod/allure-report
          subfolder: prod
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
      - name: Push image
        run: |
          docker push ${{ env.IMAGE }}
